# Generated by Django 4.1.3 on 2022-11-28 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem', '0001_initial'),
        ('Pessoa', '0002_pessoa_garagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fabricacao', models.DateField(verbose_name='Data de fabricação')),
                ('modelo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modelo do veículo')),
                ('cor', models.CharField(blank=True, max_length=250, null=True, verbose_name='Cor do veículo')),
                ('tipo', models.IntegerField(choices=[(1, 'Carro'), (2, 'Moto')], verbose_name='Tipo')),
                ('garagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Garagem.garagem')),
            ],
        ),
    ]
