# Generated by Django 4.1.3 on 2022-11-29 06:08

import Garagem.models.veiculo
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fabricacao', models.DateField(verbose_name='Data de fabricação')),
                ('modelo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Modelo do veículo')),
                ('cor', models.CharField(blank=True, max_length=250, null=True, verbose_name='Cor do veículo')),
                ('tipo', models.IntegerField(choices=[(1, 'Carro'), (2, 'Moto')], verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Garagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250, verbose_name='E-mail')),
                ('celular', models.CharField(max_length=250, verbose_name='Número de celular')),
                ('veiculos', models.ManyToManyField(default=Garagem.models.veiculo.Veiculo, to='Garagem.veiculo')),
            ],
        ),
    ]
