# Generated by Django 4.1.3 on 2022-11-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Garagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='garagem',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Garagem ativa'),
        ),
    ]
